//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorBlindPicker.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorBlindPicker.Resources.Localizations.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Bright0 {
            get {
                return ResourceManager.GetString("Bright0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darkest.
        /// </summary>
        internal static string Bright0_1 {
            get {
                return ResourceManager.GetString("Bright0.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Bright0_3 {
            get {
                return ResourceManager.GetString("Bright0.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal br.
        /// </summary>
        internal static string Bright0_5 {
            get {
                return ResourceManager.GetString("Bright0.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Bright0_7 {
            get {
                return ResourceManager.GetString("Bright0.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very light.
        /// </summary>
        internal static string Bright0_9 {
            get {
                return ResourceManager.GetString("Bright0.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string Bright1 {
            get {
                return ResourceManager.GetString("Bright1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CaptionClose {
            get {
                return ResourceManager.GetString("CaptionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        internal static string CaptionCopied {
            get {
                return ResourceManager.GetString("CaptionCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CaptionCopy {
            get {
                return ResourceManager.GetString("CaptionCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CaptionDelete {
            get {
                return ResourceManager.GetString("CaptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string CaptionHistory {
            get {
                return ResourceManager.GetString("CaptionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string CaptionLanguage {
            get {
                return ResourceManager.GetString("CaptionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker.
        /// </summary>
        internal static string CaptionPicker {
            get {
                return ResourceManager.GetString("CaptionPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin at the top.
        /// </summary>
        internal static string CaptionPin {
            get {
                return ResourceManager.GetString("CaptionPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CaptionSettings {
            get {
                return ResourceManager.GetString("CaptionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Hue0 {
            get {
                return ResourceManager.GetString("Hue0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange red.
        /// </summary>
        internal static string Hue10 {
            get {
                return ResourceManager.GetString("Hue10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring green.
        /// </summary>
        internal static string Hue100 {
            get {
                return ResourceManager.GetString("Hue100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light green.
        /// </summary>
        internal static string Hue110 {
            get {
                return ResourceManager.GetString("Hue110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald green.
        /// </summary>
        internal static string Hue120 {
            get {
                return ResourceManager.GetString("Hue120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest green.
        /// </summary>
        internal static string Hue130 {
            get {
                return ResourceManager.GetString("Hue130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive green.
        /// </summary>
        internal static string Hue140 {
            get {
                return ResourceManager.GetString("Hue140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua green.
        /// </summary>
        internal static string Hue150 {
            get {
                return ResourceManager.GetString("Hue150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise green.
        /// </summary>
        internal static string Hue160 {
            get {
                return ResourceManager.GetString("Hue160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise blue.
        /// </summary>
        internal static string Hue170 {
            get {
                return ResourceManager.GetString("Hue170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string Hue180 {
            get {
                return ResourceManager.GetString("Hue180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise blue.
        /// </summary>
        internal static string Hue190 {
            get {
                return ResourceManager.GetString("Hue190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddish orange.
        /// </summary>
        internal static string Hue20 {
            get {
                return ResourceManager.GetString("Hue20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenish blue.
        /// </summary>
        internal static string Hue200 {
            get {
                return ResourceManager.GetString("Hue200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Hue210 {
            get {
                return ResourceManager.GetString("Hue210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean blue.
        /// </summary>
        internal static string Hue220 {
            get {
                return ResourceManager.GetString("Hue220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal blue.
        /// </summary>
        internal static string Hue230 {
            get {
                return ResourceManager.GetString("Hue230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight blue.
        /// </summary>
        internal static string Hue240 {
            get {
                return ResourceManager.GetString("Hue240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo blue.
        /// </summary>
        internal static string Hue250 {
            get {
                return ResourceManager.GetString("Hue250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluish purple.
        /// </summary>
        internal static string Hue260 {
            get {
                return ResourceManager.GetString("Hue260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Hue270 {
            get {
                return ResourceManager.GetString("Hue270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggplant purple.
        /// </summary>
        internal static string Hue280 {
            get {
                return ResourceManager.GetString("Hue280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amethyst purple.
        /// </summary>
        internal static string Hue290 {
            get {
                return ResourceManager.GetString("Hue290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Hue30 {
            get {
                return ResourceManager.GetString("Hue30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta.
        /// </summary>
        internal static string Hue300 {
            get {
                return ResourceManager.GetString("Hue300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclamen pink.
        /// </summary>
        internal static string Hue310 {
            get {
                return ResourceManager.GetString("Hue310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright pink.
        /// </summary>
        internal static string Hue320 {
            get {
                return ResourceManager.GetString("Hue320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta red.
        /// </summary>
        internal static string Hue330 {
            get {
                return ResourceManager.GetString("Hue330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby red.
        /// </summary>
        internal static string Hue340 {
            get {
                return ResourceManager.GetString("Hue340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright red .
        /// </summary>
        internal static string Hue350 {
            get {
                return ResourceManager.GetString("Hue350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Hue360 {
            get {
                return ResourceManager.GetString("Hue360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden orange.
        /// </summary>
        internal static string Hue40 {
            get {
                return ResourceManager.GetString("Hue40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow orange.
        /// </summary>
        internal static string Hue50 {
            get {
                return ResourceManager.GetString("Hue50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Hue60 {
            get {
                return ResourceManager.GetString("Hue60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemon yellow.
        /// </summary>
        internal static string Hue70 {
            get {
                return ResourceManager.GetString("Hue70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenish yellow.
        /// </summary>
        internal static string Hue80 {
            get {
                return ResourceManager.GetString("Hue80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Hue90 {
            get {
                return ResourceManager.GetString("Hue90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string Sat0 {
            get {
                return ResourceManager.GetString("Sat0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayish.
        /// </summary>
        internal static string Sat0_25 {
            get {
                return ResourceManager.GetString("Sat0.25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faded.
        /// </summary>
        internal static string Sat0_5 {
            get {
                return ResourceManager.GetString("Sat0.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slightly faded.
        /// </summary>
        internal static string Sat0_75 {
            get {
                return ResourceManager.GetString("Sat0.75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal sat.
        /// </summary>
        internal static string Sat1 {
            get {
                return ResourceManager.GetString("Sat1", resourceCulture);
            }
        }
    }
}
